# Generated by Django 3.2.9 on 2023-02-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('complexity', models.IntegerField(choices=[('0', 'Elementary'), ('1', 'Simple'), ('2', 'Moderate'), ('3', 'High'), ('4', 'Advanced'), ('5', 'Extreme')])),
                ('deadline', models.DateField()),
                ('status', models.IntegerField(choices=[('0', 'Open'), ('1', 'Picked'), ('2', 'Completed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
